version: "3"
services:
  node-app:
    build: .
    ports:
    - 2000:3524
  jenkins-app:
    image: jenkins/jenkins:lts
    build: dockerInstall/
    privileged: true
    user: root
    ports:
    - 2001:8080
    - 50000:50000
    container_name: jenkins
    volumes:
    - ~/jenkins:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/local/bin/docker:/usr/local/bin/docker
